/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package attendance.management.system;

import java.awt.Color;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Asus
 */
public class AdminRegisterstudent extends javax.swing.JFrame {

    
    public AdminRegisterstudent() {
        initComponents();
    }
    
    void setColor(JPanel panel){
        panel.setBackground(new Color(85,65,200));
    }
    
    void resetColor(JPanel panel){
        panel.setBackground(new Color(85,65,153));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BG = new javax.swing.JPanel();
        Sidepane = new javax.swing.JPanel();
        Registerbutton = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Profilebutton = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Viewbutton = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Searchbutton = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        Motifybutton = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        Namelabel = new javax.swing.JLabel();
        Attendancebutton = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        Exitbutton = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        phonefield = new javax.swing.JTextField();
        firstnamefield = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        idfield = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        emailfield = new javax.swing.JTextField();
        racefield = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        religionfield = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        coursefield = new javax.swing.JTextField();
        addfield = new javax.swing.JTextField();
        nationfield = new javax.swing.JTextField();
        passfield = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        lastnamefield = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        subject = new javax.swing.JTextField();
        lecturer1 = new javax.swing.JTextField();
        subject2 = new javax.swing.JTextField();
        lecturer2 = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel40 = new javax.swing.JLabel();
        years = new javax.swing.JComboBox<>();
        months = new javax.swing.JComboBox<>();
        days = new javax.swing.JComboBox<>();
        intakecombo = new javax.swing.JComboBox<>();
        sexcombo = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        BG.setBackground(new java.awt.Color(255, 255, 255));
        BG.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        BG.setEnabled(false);
        BG.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                BGMouseMoved(evt);
            }
        });
        BG.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Sidepane.setBackground(new java.awt.Color(51, 0, 102));
        Sidepane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Registerbutton.setBackground(new java.awt.Color(85, 65, 200));
        Registerbutton.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                RegisterbuttonMouseMoved(evt);
            }
        });
        Registerbutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                RegisterbuttonMousePressed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Add User Male_48px_1.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Register");

        javax.swing.GroupLayout RegisterbuttonLayout = new javax.swing.GroupLayout(Registerbutton);
        Registerbutton.setLayout(RegisterbuttonLayout);
        RegisterbuttonLayout.setHorizontalGroup(
            RegisterbuttonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RegisterbuttonLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        RegisterbuttonLayout.setVerticalGroup(
            RegisterbuttonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        Sidepane.add(Registerbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 460, 330, -1));

        Profilebutton.setBackground(new java.awt.Color(85, 65, 153));
        Profilebutton.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                ProfilebuttonMouseMoved(evt);
            }
        });
        Profilebutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                ProfilebuttonMouseReleased(evt);
            }
        });
        Profilebutton.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/User_48px.png"))); // NOI18N
        Profilebutton.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 0, 61, 60));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Profile");
        Profilebutton.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(133, 0, 109, 60));

        Sidepane.add(Profilebutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 330, -1));

        Viewbutton.setBackground(new java.awt.Color(85, 65, 153));
        Viewbutton.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                ViewbuttonMouseMoved(evt);
            }
        });
        Viewbutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ViewbuttonMousePressed(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/View Details_48px.png"))); // NOI18N

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("View");

        javax.swing.GroupLayout ViewbuttonLayout = new javax.swing.GroupLayout(Viewbutton);
        Viewbutton.setLayout(ViewbuttonLayout);
        ViewbuttonLayout.setHorizontalGroup(
            ViewbuttonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ViewbuttonLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        ViewbuttonLayout.setVerticalGroup(
            ViewbuttonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        Sidepane.add(Viewbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 330, -1));

        Searchbutton.setBackground(new java.awt.Color(85, 65, 153));
        Searchbutton.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                SearchbuttonMouseMoved(evt);
            }
        });
        Searchbutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                SearchbuttonMousePressed(evt);
            }
        });

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Search_48px.png"))); // NOI18N

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Search & Delete");

        javax.swing.GroupLayout SearchbuttonLayout = new javax.swing.GroupLayout(Searchbutton);
        Searchbutton.setLayout(SearchbuttonLayout);
        SearchbuttonLayout.setHorizontalGroup(
            SearchbuttonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SearchbuttonLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE)
                .addContainerGap())
        );
        SearchbuttonLayout.setVerticalGroup(
            SearchbuttonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        Sidepane.add(Searchbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 340, 330, -1));

        Motifybutton.setBackground(new java.awt.Color(85, 65, 153));
        Motifybutton.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                MotifybuttonMouseMoved(evt);
            }
        });
        Motifybutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                MotifybuttonMousePressed(evt);
            }
        });

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Change User_48px.png"))); // NOI18N

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Modify");

        javax.swing.GroupLayout MotifybuttonLayout = new javax.swing.GroupLayout(Motifybutton);
        Motifybutton.setLayout(MotifybuttonLayout);
        MotifybuttonLayout.setHorizontalGroup(
            MotifybuttonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MotifybuttonLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        MotifybuttonLayout.setVerticalGroup(
            MotifybuttonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        Sidepane.add(Motifybutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 400, 330, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Male User_96px.png"))); // NOI18N
        Sidepane.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, -1, 90));

        Namelabel.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        Namelabel.setForeground(new java.awt.Color(255, 255, 255));
        Namelabel.setText("User");
        Sidepane.add(Namelabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, -1, -1));

        Attendancebutton.setBackground(new java.awt.Color(85, 65, 153));
        Attendancebutton.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                AttendancebuttonMouseMoved(evt);
            }
        });
        Attendancebutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                AttendancebuttonMousePressed(evt);
            }
        });

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Classroom_48px.png"))); // NOI18N

        jLabel24.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("Attendance");

        javax.swing.GroupLayout AttendancebuttonLayout = new javax.swing.GroupLayout(Attendancebutton);
        Attendancebutton.setLayout(AttendancebuttonLayout);
        AttendancebuttonLayout.setHorizontalGroup(
            AttendancebuttonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AttendancebuttonLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        AttendancebuttonLayout.setVerticalGroup(
            AttendancebuttonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        Sidepane.add(Attendancebutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 520, 330, -1));

        BG.add(Sidepane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 330, 850));

        jPanel3.setBackground(new java.awt.Color(153, 102, 255));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 34)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Student Register");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Admin");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(jLabel12))
                .addContainerGap(240, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        BG.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 110, 600, 150));

        Exitbutton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Cancel_24px_1.png"))); // NOI18N
        Exitbutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ExitbuttonMousePressed(evt);
            }
        });
        BG.add(Exitbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 10, -1, -1));

        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Exit Sign_30px.png"))); // NOI18N
        jLabel25.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel25MousePressed(evt);
            }
        });
        BG.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 7, -1, -1));
        BG.add(phonefield, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 630, 182, -1));
        BG.add(firstnamefield, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 270, 182, -1));

        jLabel22.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel22.setText("Religion:");
        BG.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 510, -1, -1));
        BG.add(idfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 350, 182, -1));

        jLabel31.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel31.setText("Last name:");
        BG.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 310, -1, -1));

        jLabel19.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel19.setText("Password:");
        BG.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 510, -1, -1));
        BG.add(emailfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 590, 182, -1));
        BG.add(racefield, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 550, 182, -1));

        jLabel20.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel20.setText("Student ID:");
        BG.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 350, -1, -1));

        jLabel21.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel21.setText("Nationality:");
        BG.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 470, -1, -1));
        BG.add(religionfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 510, 182, -1));

        jLabel26.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel26.setText("Address:");
        BG.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 670, -1, -1));

        jLabel30.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel30.setText("Sex:");
        BG.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 390, -1, -1));
        BG.add(coursefield, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 310, 130, -1));
        BG.add(addfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 670, 320, 74));
        BG.add(nationfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 470, 182, -1));
        BG.add(passfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 510, 130, -1));

        jLabel33.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel33.setText("Intake:");
        BG.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 270, -1, -1));

        jLabel28.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel28.setText("Student Email:");
        BG.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 590, -1, -1));

        jLabel27.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel27.setText("Mobile Phone:");
        BG.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 630, -1, -1));
        BG.add(lastnamefield, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 310, 182, -1));

        jLabel32.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel32.setText("First name:");
        BG.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 270, -1, -1));

        jLabel18.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel18.setText("Date of Birth:");
        BG.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 430, -1, -1));

        jLabel29.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel29.setText("Race:");
        BG.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 550, -1, -1));
        BG.add(subject, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 350, 130, -1));
        BG.add(lecturer1, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 390, 130, -1));
        BG.add(subject2, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 430, 130, -1));
        BG.add(lecturer2, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 470, 130, -1));

        jLabel35.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel35.setText("Subject 1:");
        BG.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 350, -1, -1));

        jLabel36.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel36.setText("Subject 2:");
        BG.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 430, -1, -1));

        jLabel38.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel38.setText("Lecturer1:");
        BG.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 390, -1, -1));

        jLabel39.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel39.setText("Lecturer2:");
        BG.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 470, -1, -1));

        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton1.setText("Register");
        jButton1.setFocusable(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        BG.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 760, -1, -1));

        jLabel40.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel40.setText("Course:");
        BG.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 310, -1, -1));

        years.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        years.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2017", "2016", "2015", "2014", "2013", "2012", "2011", "2010", "2009", "2008", "2007", "2006", "2005", "2004", "2003", "2002", "2001", "2000", "1999", "1998", "1997", "1996", "1995", "1994", "1993", "1992", "1991", "1990", "1989", "1988", "1987", "1986", "1985", "1984", "1983", "1982", "1981", "1980", "1979", "1978", "1977", "1976", "1975", "1974", "1973", "1972", "1971", "1970", "1969", "1968", "1967", "1966", "1965", "1964", "1963", "1962", "1961", "1960", "1959", "1958", "1957", "1956", "1955", "1954", "1953", "1952", "1951" }));
        BG.add(years, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 430, -1, -1));

        months.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        months.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December" }));
        BG.add(months, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 430, 90, -1));

        days.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        days.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        BG.add(days, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 430, -1, -1));

        intakecombo.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        intakecombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "UC1F1605", "UC1F1705" }));
        BG.add(intakecombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 270, 130, -1));

        sexcombo.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        sexcombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));
        BG.add(sexcombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 390, 180, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BG, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BG, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ExitbuttonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitbuttonMousePressed
        // TODO add your handling code here:
        int closeprogram = JOptionPane.showConfirmDialog(null,"Do you want to exit system?","Exit",
                JOptionPane.YES_NO_OPTION);
        if (closeprogram == JOptionPane.YES_OPTION)
        {
        System.exit(0);
        }
    }//GEN-LAST:event_ExitbuttonMousePressed

    private void BGMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BGMouseMoved
        // TODO add your handling code here:
        setColor(Registerbutton);
        resetColor(Viewbutton);
        resetColor(Searchbutton);
        resetColor(Motifybutton);
        resetColor(Profilebutton);
        resetColor(Attendancebutton);
    }//GEN-LAST:event_BGMouseMoved

    private void ViewbuttonMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ViewbuttonMouseMoved
        // TODO add your handling code here:
        setColor(Viewbutton);
        resetColor(Profilebutton);
        resetColor(Searchbutton);
        resetColor(Motifybutton);
        resetColor(Registerbutton);
        resetColor(Attendancebutton);
    }//GEN-LAST:event_ViewbuttonMouseMoved

    private void SearchbuttonMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SearchbuttonMouseMoved
        // TODO add your handling code here:
        setColor(Searchbutton);
        resetColor(Profilebutton);
        resetColor(Viewbutton);
        resetColor(Motifybutton);
        resetColor(Registerbutton);
        resetColor(Attendancebutton);
    }//GEN-LAST:event_SearchbuttonMouseMoved

    private void MotifybuttonMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MotifybuttonMouseMoved
        // TODO add your handling code here:
        setColor(Motifybutton);
        resetColor(Profilebutton);
        resetColor(Searchbutton);
        resetColor(Viewbutton);
        resetColor(Registerbutton);
        resetColor(Attendancebutton);
    }//GEN-LAST:event_MotifybuttonMouseMoved

    private void RegisterbuttonMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegisterbuttonMouseMoved
        // TODO add your handling code here:
        setColor(Registerbutton);
        resetColor(Profilebutton);
        resetColor(Searchbutton);
        resetColor(Motifybutton);
        resetColor(Viewbutton);
        resetColor(Attendancebutton);
    }//GEN-LAST:event_RegisterbuttonMouseMoved

    private void AttendancebuttonMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AttendancebuttonMouseMoved
        // TODO add your handling code here:
        setColor(Attendancebutton);
        resetColor(Profilebutton);
        resetColor(Searchbutton);
        resetColor(Motifybutton);
        resetColor(Viewbutton);
        resetColor(Registerbutton);
    }//GEN-LAST:event_AttendancebuttonMouseMoved

    private void ViewbuttonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ViewbuttonMousePressed
        // TODO add your handling code here:
        AdminView view = new AdminView();
        view.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_ViewbuttonMousePressed

    private void SearchbuttonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SearchbuttonMousePressed
        // TODO add your handling code here:
        AdminSearch search = new AdminSearch();
        search.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_SearchbuttonMousePressed

    private void MotifybuttonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MotifybuttonMousePressed
        // TODO add your handling code here:
        AdminMotify motify = new AdminMotify();
        motify.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_MotifybuttonMousePressed

    private void AttendancebuttonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AttendancebuttonMousePressed
        // TODO add your handling code here:
        AdminAttendance attendance = new AdminAttendance();
        attendance.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_AttendancebuttonMousePressed

    private void jLabel25MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel25MousePressed
        // TODO add your handling code here:
        int logout = JOptionPane.showConfirmDialog(null,"Do you want to logout ID?","Logout",
            JOptionPane.YES_NO_OPTION);
        if (logout == JOptionPane.YES_OPTION)
        {
            Loginpage login = new Loginpage();
            login.setVisible(true);
            this.setVisible(false);
        }
    }//GEN-LAST:event_jLabel25MousePressed

    private void ProfilebuttonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ProfilebuttonMouseReleased
        // TODO add your handling code here:
        Admin profile = new Admin();
        profile.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_ProfilebuttonMouseReleased

    private void ProfilebuttonMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ProfilebuttonMouseMoved
        // TODO add your handling code here:
        setColor(Profilebutton);
        resetColor(Attendancebutton);
        resetColor(Searchbutton);
        resetColor(Motifybutton);
        resetColor(Viewbutton);
        resetColor(Registerbutton);
    }//GEN-LAST:event_ProfilebuttonMouseMoved

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        adminclass ad = new adminclass();
        ad.getFirstName(firstnamefield.getText());
        ad.getLastName(lastnamefield.getText());
        ad.getPass(passfield.getText());
        String full = ad.fullname();
        String ID = ad.ID();
        String in = intakecombo.getSelectedItem().toString();
        
        //Get DOB through combo box and generate in class
        ad.getDay(days.getSelectedItem().toString());
        ad.getMonth(months.getSelectedItem().toString());
        ad.getYear(years.getSelectedItem().toString());
        String dob = ad.DOB();
        
        //Create a new file following student name
        try{
            File file = new File(full+".txt");
            file.createNewFile();
            
            FileWriter fw = new FileWriter(file.getAbsoluteFile());
            BufferedWriter bw = new BufferedWriter(fw);
            bw.write(firstnamefield.getText()+"\n");
            bw.write(lastnamefield.getText()+"\n");
            bw.write(idfield.getText()+"\n");
            bw.write(sexcombo.getSelectedItem().toString()+"\n");
            bw.write(dob+"\n");
            bw.write(nationfield.getText()+"\n");
            bw.write(religionfield.getText()+"\n");
            bw.write(racefield.getText()+"\n");
            bw.write(emailfield.getText()+"\n");
            bw.write(phonefield.getText()+"\n");
            bw.write(addfield.getText()+"\n");
            bw.write(in+"\n");
            bw.write(coursefield.getText()+"\n");
            bw.write(subject.getText()+"\n");
            bw.write(lecturer1.getText()+"\n");
            bw.write(subject2.getText()+"\n");
            bw.write(lecturer2.getText()+"\n");
            bw.write(passfield.getText());
            
            bw.close();
            fw.close();
            
            
        } catch(Exception e){
            e.printStackTrace();
        }
        
        //Write Student ID inside studentlogin.txt so that he can login
        try{
            FileWriter fw = new FileWriter("studentlogin.txt",true);
            BufferedWriter bw = new BufferedWriter(fw);
            
            bw.write(ID);
            bw.write("\n");
            bw.close();
            fw.close();
    
        } catch(Exception e){
            e.printStackTrace();
        }
        
        //Write student information inside general student txt file
        try{
            FileWriter fw = new FileWriter("ALLstudents.txt",true);
            BufferedWriter bw = new BufferedWriter(fw);
            bw.write(full+"|"+idfield.getText()+"|"+in+"|"+coursefield.getText());
            bw.write("\n");
            bw.close();
            fw.close();
    
        } catch(Exception e){
            e.printStackTrace();
        }
        
        //this process will write to lecturer1 file whom assign to
        try{
            String intake1 = lecturer1.getText() + in;
            FileWriter fw = new FileWriter(intake1+".txt",true);
            BufferedWriter bw = new BufferedWriter(fw);
            bw.write(full+"|"+idfield.getText()+"|"+subject.getText()+"|"+in+"|"+coursefield.getText());
            bw.write("\n");
            bw.close();
            fw.close();
    
        } catch(Exception e){
            e.printStackTrace();
        }
        
        //this process will write to lecturer2 file whom assign to
        try{
            String intake2 = lecturer2.getText() + in;
            FileWriter fw = new FileWriter(intake2+".txt",true);
            BufferedWriter bw = new BufferedWriter(fw);
            bw.write(full+"|"+idfield.getText()+"|"+subject2.getText()+"|"+in+"|"+coursefield.getText());
            bw.write("\n");
            bw.close();
            fw.close();
    
        } catch(Exception e){
            e.printStackTrace();
        }
        
        
        //create a student attendance txt file
        try{
            File file = new File(full+in+"attendance.txt");
            file.createNewFile();
   
            
        } catch(Exception e){
            e.printStackTrace();
        }
        
        JOptionPane.showMessageDialog(null, "Register Successfully!");
        firstnamefield.setText("");
        lastnamefield.setText("");
        idfield.setText("");
        nationfield.setText("");
        religionfield.setText("");
        racefield.setText("");
        emailfield.setText("");
        phonefield.setText("");
        addfield.setText("");
        coursefield.setText("");
        subject.setText("");
        lecturer1.setText("");
        subject2.setText("");
        lecturer2.setText("");
        passfield.setText("");
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void RegisterbuttonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegisterbuttonMousePressed
        AdminRegister register = new AdminRegister();
        register.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_RegisterbuttonMousePressed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        adminclass a = new adminclass();
        String name = a.full();
        Namelabel.setText(name);
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminRegisterstudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminRegisterstudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminRegisterstudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminRegisterstudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminRegisterstudent().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Attendancebutton;
    private javax.swing.JPanel BG;
    private javax.swing.JLabel Exitbutton;
    private javax.swing.JPanel Motifybutton;
    private javax.swing.JLabel Namelabel;
    private javax.swing.JPanel Profilebutton;
    private javax.swing.JPanel Registerbutton;
    private javax.swing.JPanel Searchbutton;
    private javax.swing.JPanel Sidepane;
    private javax.swing.JPanel Viewbutton;
    private javax.swing.JTextField addfield;
    private javax.swing.JTextField coursefield;
    private javax.swing.JComboBox<String> days;
    private javax.swing.JTextField emailfield;
    private javax.swing.JTextField firstnamefield;
    private javax.swing.JTextField idfield;
    private javax.swing.JComboBox<String> intakecombo;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField lastnamefield;
    private javax.swing.JTextField lecturer1;
    private javax.swing.JTextField lecturer2;
    private javax.swing.JComboBox<String> months;
    private javax.swing.JTextField nationfield;
    private javax.swing.JTextField passfield;
    private javax.swing.JTextField phonefield;
    private javax.swing.JTextField racefield;
    private javax.swing.JTextField religionfield;
    private javax.swing.JComboBox<String> sexcombo;
    private javax.swing.JTextField subject;
    private javax.swing.JTextField subject2;
    private javax.swing.JComboBox<String> years;
    // End of variables declaration//GEN-END:variables
}
