/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package attendance.management.system;

import java.awt.Color;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileWriter;
import java.util.Scanner;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Asus
 */
public class AdminMotifylecturer extends javax.swing.JFrame {

    
    public AdminMotifylecturer() {
        initComponents();
    }
    
    void setColor(JPanel panel){
        panel.setBackground(new Color(85,65,200));
    }
    
    void resetColor(JPanel panel){
        panel.setBackground(new Color(85,65,153));
        
    }
    
    void resetColor1(JPanel panel){
        panel.setBackground(new Color(204,204,255));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BG = new javax.swing.JPanel();
        Sidepane = new javax.swing.JPanel();
        Registerbutton = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Profilebutton = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Viewbutton = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Searchbutton = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        Motifybutton = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        Namelabel = new javax.swing.JLabel();
        Attendancebutton = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        Exitbutton = new javax.swing.JLabel();
        Findbutton = new javax.swing.JButton();
        IDinput = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        firstnamefield = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        lastnamefield = new javax.swing.JTextField();
        idfield = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        sexfield = new javax.swing.JTextField();
        dobfield = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        nationfield = new javax.swing.JTextField();
        religionfield = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        racefield = new javax.swing.JTextField();
        emailfield = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        phonefield = new javax.swing.JTextField();
        addfield = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        passfield = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        intakefield2 = new javax.swing.JTextField();
        intakefield = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        subjectfield = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        BG.setBackground(new java.awt.Color(255, 255, 255));
        BG.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        BG.setEnabled(false);
        BG.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                BGMouseMoved(evt);
            }
        });
        BG.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Sidepane.setBackground(new java.awt.Color(51, 0, 102));
        Sidepane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Registerbutton.setBackground(new java.awt.Color(85, 65, 153));
        Registerbutton.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                RegisterbuttonMouseMoved(evt);
            }
        });
        Registerbutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                RegisterbuttonMousePressed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Add User Male_48px_1.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Register");

        javax.swing.GroupLayout RegisterbuttonLayout = new javax.swing.GroupLayout(Registerbutton);
        Registerbutton.setLayout(RegisterbuttonLayout);
        RegisterbuttonLayout.setHorizontalGroup(
            RegisterbuttonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RegisterbuttonLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        RegisterbuttonLayout.setVerticalGroup(
            RegisterbuttonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        Sidepane.add(Registerbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 460, 330, -1));

        Profilebutton.setBackground(new java.awt.Color(85, 65, 153));
        Profilebutton.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                ProfilebuttonMouseMoved(evt);
            }
        });
        Profilebutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ProfilebuttonMousePressed(evt);
            }
        });
        Profilebutton.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/User_48px.png"))); // NOI18N
        Profilebutton.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 0, 61, 60));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Profile");
        Profilebutton.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(133, 0, 109, 60));

        Sidepane.add(Profilebutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 330, -1));

        Viewbutton.setBackground(new java.awt.Color(85, 65, 153));
        Viewbutton.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                ViewbuttonMouseMoved(evt);
            }
        });
        Viewbutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ViewbuttonMousePressed(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/View Details_48px.png"))); // NOI18N

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("View");

        javax.swing.GroupLayout ViewbuttonLayout = new javax.swing.GroupLayout(Viewbutton);
        Viewbutton.setLayout(ViewbuttonLayout);
        ViewbuttonLayout.setHorizontalGroup(
            ViewbuttonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ViewbuttonLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        ViewbuttonLayout.setVerticalGroup(
            ViewbuttonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        Sidepane.add(Viewbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 330, -1));

        Searchbutton.setBackground(new java.awt.Color(85, 65, 153));
        Searchbutton.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                SearchbuttonMouseMoved(evt);
            }
        });
        Searchbutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                SearchbuttonMousePressed(evt);
            }
        });

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Search_48px.png"))); // NOI18N

        jLabel8.setBackground(new java.awt.Color(240, 240, 153));
        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Search & Delete");

        javax.swing.GroupLayout SearchbuttonLayout = new javax.swing.GroupLayout(Searchbutton);
        Searchbutton.setLayout(SearchbuttonLayout);
        SearchbuttonLayout.setHorizontalGroup(
            SearchbuttonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SearchbuttonLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE)
                .addContainerGap())
        );
        SearchbuttonLayout.setVerticalGroup(
            SearchbuttonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        Sidepane.add(Searchbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 340, 330, -1));

        Motifybutton.setBackground(new java.awt.Color(85, 65, 200));
        Motifybutton.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                MotifybuttonMouseMoved(evt);
            }
        });
        Motifybutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                MotifybuttonMousePressed(evt);
            }
        });

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Change User_48px.png"))); // NOI18N

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Modify");

        javax.swing.GroupLayout MotifybuttonLayout = new javax.swing.GroupLayout(Motifybutton);
        Motifybutton.setLayout(MotifybuttonLayout);
        MotifybuttonLayout.setHorizontalGroup(
            MotifybuttonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MotifybuttonLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        MotifybuttonLayout.setVerticalGroup(
            MotifybuttonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        Sidepane.add(Motifybutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 400, 330, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Male User_96px.png"))); // NOI18N
        Sidepane.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, -1, 90));

        Namelabel.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        Namelabel.setForeground(new java.awt.Color(255, 255, 255));
        Namelabel.setText("User");
        Sidepane.add(Namelabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, -1, -1));

        Attendancebutton.setBackground(new java.awt.Color(85, 65, 153));
        Attendancebutton.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                AttendancebuttonMouseMoved(evt);
            }
        });
        Attendancebutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                AttendancebuttonMousePressed(evt);
            }
        });

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Classroom_48px.png"))); // NOI18N

        jLabel24.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("Attendance");

        javax.swing.GroupLayout AttendancebuttonLayout = new javax.swing.GroupLayout(Attendancebutton);
        Attendancebutton.setLayout(AttendancebuttonLayout);
        AttendancebuttonLayout.setHorizontalGroup(
            AttendancebuttonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AttendancebuttonLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        AttendancebuttonLayout.setVerticalGroup(
            AttendancebuttonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        Sidepane.add(Attendancebutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 520, 330, -1));

        BG.add(Sidepane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 330, 850));

        jPanel3.setBackground(new java.awt.Color(153, 102, 255));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 34)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Modify Profile");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Admin");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(jLabel12))
                .addContainerGap(274, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        BG.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 110, 600, 150));

        Exitbutton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Cancel_24px_1.png"))); // NOI18N
        Exitbutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ExitbuttonMousePressed(evt);
            }
        });
        BG.add(Exitbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 10, -1, -1));

        Findbutton.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        Findbutton.setText("Enter");
        Findbutton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Findbutton.setFocusable(false);
        Findbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FindbuttonActionPerformed(evt);
            }
        });
        BG.add(Findbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 270, 90, 30));

        IDinput.setFont(new java.awt.Font("Malgun Gothic", 0, 18)); // NOI18N
        IDinput.setText("Enter ID");
        IDinput.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        IDinput.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                IDinputMouseClicked(evt);
            }
        });
        BG.add(IDinput, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 270, 210, 30));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Exit Sign_30px.png"))); // NOI18N
        jLabel14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel14MousePressed(evt);
            }
        });
        BG.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 7, -1, -1));
        BG.add(firstnamefield, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 320, 182, -1));

        jLabel32.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel32.setText("First name:");
        BG.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 320, -1, -1));

        jLabel31.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel31.setText("Last name:");
        BG.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 360, -1, -1));
        BG.add(lastnamefield, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 360, 182, -1));
        BG.add(idfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 400, 182, -1));

        jLabel20.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel20.setText("Staff ID:");
        BG.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 400, -1, -1));

        jLabel30.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel30.setText("Sex:");
        BG.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 440, -1, -1));
        BG.add(sexfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 440, 182, -1));
        BG.add(dobfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 480, 180, -1));

        jLabel18.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel18.setText("Date of Birth:");
        BG.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 480, -1, -1));

        jLabel21.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel21.setText("Nationality:");
        BG.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 520, -1, -1));
        BG.add(nationfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 520, 182, -1));
        BG.add(religionfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 560, 182, -1));

        jLabel22.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel22.setText("Religion:");
        BG.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 560, -1, -1));

        jLabel29.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel29.setText("Race:");
        BG.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 600, -1, -1));
        BG.add(racefield, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 600, 182, -1));
        BG.add(emailfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 640, 182, -1));

        jLabel28.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel28.setText("Staff Email:");
        BG.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 640, -1, -1));

        jLabel27.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel27.setText("Mobile Phone:");
        BG.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 680, -1, -1));
        BG.add(phonefield, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 680, 182, -1));
        BG.add(addfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 720, 320, 74));

        jLabel26.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel26.setText("Address:");
        BG.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 720, -1, -1));
        BG.add(passfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 440, 130, -1));

        jLabel19.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel19.setText("Password:");
        BG.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 440, -1, -1));

        jLabel33.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel33.setText("Intake 2:");
        BG.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 400, -1, -1));

        intakefield2.setEditable(false);
        BG.add(intakefield2, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 400, 130, -1));

        intakefield.setEditable(false);
        BG.add(intakefield, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 360, 130, -1));

        jLabel35.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel35.setText("Intake:");
        BG.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 360, -1, -1));

        jLabel34.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel34.setText("Subject:");
        BG.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 320, -1, -1));

        subjectfield.setEditable(false);
        BG.add(subjectfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 320, 130, -1));

        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton1.setText("Edit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        BG.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 810, 100, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BG, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BG, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BGMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BGMouseMoved
        // TODO add your handling code here:
        setColor(Motifybutton);
        resetColor(Profilebutton);
        resetColor(Viewbutton);
        resetColor(Searchbutton);
        resetColor(Attendancebutton);
        resetColor(Registerbutton);
    }//GEN-LAST:event_BGMouseMoved

    private void ViewbuttonMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ViewbuttonMouseMoved
        // TODO add your handling code here:
        setColor(Viewbutton);
        resetColor(Profilebutton);
        resetColor(Searchbutton);
        resetColor(Motifybutton);
        resetColor(Attendancebutton);
        resetColor(Registerbutton);
    }//GEN-LAST:event_ViewbuttonMouseMoved

    private void SearchbuttonMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SearchbuttonMouseMoved
        // TODO add your handling code here:
        setColor(Searchbutton);
        resetColor(Profilebutton);
        resetColor(Viewbutton);
        resetColor(Motifybutton);
        resetColor(Attendancebutton);
        resetColor(Registerbutton);
    }//GEN-LAST:event_SearchbuttonMouseMoved

    private void MotifybuttonMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MotifybuttonMouseMoved
        // TODO add your handling code here:
        setColor(Motifybutton);
        resetColor(Profilebutton);
        resetColor(Searchbutton);
        resetColor(Viewbutton);
        resetColor(Attendancebutton);
        resetColor(Registerbutton);
    }//GEN-LAST:event_MotifybuttonMouseMoved

    private void RegisterbuttonMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegisterbuttonMouseMoved
        // TODO add your handling code heRegisterbuttonsetColor(Deletebutton);
        setColor(Registerbutton);
        resetColor(Profilebutton);
        resetColor(Searchbutton);
        resetColor(Motifybutton);
        resetColor(Viewbutton);
        resetColor(Attendancebutton);
    }//GEN-LAST:event_RegisterbuttonMouseMoved

    private void AttendancebuttonMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AttendancebuttonMouseMoved
        // TODO add your handling code here:
        setColor(Attendancebutton);
        resetColor(Profilebutton);
        resetColor(Searchbutton);
        resetColor(Motifybutton);
        resetColor(Viewbutton);
        resetColor(Registerbutton);
    }//GEN-LAST:event_AttendancebuttonMouseMoved

    private void ProfilebuttonMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ProfilebuttonMouseMoved
        // TODO add your handling code here:
        setColor(Profilebutton);
        resetColor(Attendancebutton);
        resetColor(Searchbutton);
        resetColor(Motifybutton);
        resetColor(Viewbutton);
        resetColor(Registerbutton);
    }//GEN-LAST:event_ProfilebuttonMouseMoved

    private void ProfilebuttonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ProfilebuttonMousePressed
        // TODO add your handling code here:
        Admin profile = new Admin();
        profile.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_ProfilebuttonMousePressed

    private void ExitbuttonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitbuttonMousePressed
        // TODO add your handling code here:
        int closeprogram = JOptionPane.showConfirmDialog(null,"Do you want to exit system?","Exit",
                JOptionPane.YES_NO_OPTION);
        if (closeprogram == JOptionPane.YES_OPTION)
        {
        System.exit(0);
        }
    }//GEN-LAST:event_ExitbuttonMousePressed

    private void ViewbuttonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ViewbuttonMousePressed
        // TODO add your handling code here:
        AdminView view = new AdminView();
        view.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_ViewbuttonMousePressed

    private void IDinputMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IDinputMouseClicked
        IDinput.setText("");
    }//GEN-LAST:event_IDinputMouseClicked

    private void SearchbuttonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SearchbuttonMousePressed
        // TODO add your handling code here:
        AdminSearch search = new AdminSearch();
        search.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_SearchbuttonMousePressed

    private void RegisterbuttonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegisterbuttonMousePressed
        // TODO add your handling code here:
        AdminRegister delete = new AdminRegister();
        delete.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_RegisterbuttonMousePressed

    private void AttendancebuttonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AttendancebuttonMousePressed
        // TODO add your handling code here:
        AdminAttendance attendance = new AdminAttendance();
        attendance.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_AttendancebuttonMousePressed

    private void jLabel14MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MousePressed
        // TODO add your handling code here:
        int logout = JOptionPane.showConfirmDialog(null,"Do you want to logout ID?","Logout",
            JOptionPane.YES_NO_OPTION);
        if (logout == JOptionPane.YES_OPTION)
        {
            Loginpage login = new Loginpage();
            login.setVisible(true);
            this.setVisible(false);
        }
    }//GEN-LAST:event_jLabel14MousePressed

    private void FindbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FindbuttonActionPerformed
        String name = IDinput.getText();
        /**Step 1: 
         * count how many lines.
         * Step 2:
         * Create the array and copy the elements in
         * This process will make data inside text file become array
        */
        int ctr = 0;
        try{
            Scanner sc1 = new Scanner(new File(name+".txt"));
            while (sc1.hasNextLine()){
                ctr = ctr +1;
                sc1.next();
            }
            
            String[] words = new String[ctr];
            
            Scanner sc2 = new Scanner(new File(name+".txt"));
            for (int i = 0; i < ctr; i++){
                words[i] = sc2.next();
                             
                firstnamefield.setText(words[0]);
                lastnamefield.setText(words[1]);
                idfield.setText(words[2]);
                sexfield.setText(words[3]);
                dobfield.setText(words[4]);
                nationfield.setText(words[5]);
                religionfield.setText(words[6]);
                racefield.setText(words[7]);
                emailfield.setText(words[8]);
                phonefield.setText(words[9]);
                addfield.setText(words[10]);
                subjectfield.setText(words[11]);
                intakefield.setText(words[12]);
                intakefield2.setText(words[13]);
                passfield.setText(words[14]);

                
            }
            sc2.close();
            sc1.close();
            
        } 
        catch(FileNotFoundException e){
            JOptionPane.showMessageDialog(null, "User not found!");
        }
    }//GEN-LAST:event_FindbuttonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try{
            String name = IDinput.getText();
            FileWriter fw = new FileWriter(name+".txt");
            BufferedWriter bw = new BufferedWriter(fw);

            bw.write(firstnamefield.getText()+"\n");
            bw.write(lastnamefield.getText()+"\n");
            bw.write(idfield.getText()+"\n");
            bw.write(sexfield.getText()+"\n");
            bw.write(dobfield.getText()+"\n");
            bw.write(nationfield.getText()+"\n");
            bw.write(religionfield.getText()+"\n");
            bw.write(racefield.getText()+"\n");
            bw.write(emailfield.getText()+"\n");
            bw.write(phonefield.getText()+"\n");
            bw.write(addfield.getText()+"\n");
            bw.write(intakefield.getText()+"\n");
            bw.write(subjectfield.getText()+"\n");
            bw.write(intakefield.getText()+"\n");
            bw.write(intakefield2.getText()+"\n");
            bw.write(passfield.getText());

            bw.close();
            fw.close();
            JOptionPane.showMessageDialog(null,"Saved!?");
        } catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void MotifybuttonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MotifybuttonMousePressed
        AdminMotify ad = new AdminMotify();
        ad.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_MotifybuttonMousePressed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        adminclass a = new adminclass();
        String name = a.full();
        Namelabel.setText(name);
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminMotifylecturer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminMotifylecturer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminMotifylecturer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminMotifylecturer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminMotifylecturer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Attendancebutton;
    private javax.swing.JPanel BG;
    private javax.swing.JLabel Exitbutton;
    private javax.swing.JButton Findbutton;
    private javax.swing.JTextField IDinput;
    private javax.swing.JPanel Motifybutton;
    private javax.swing.JLabel Namelabel;
    private javax.swing.JPanel Profilebutton;
    private javax.swing.JPanel Registerbutton;
    private javax.swing.JPanel Searchbutton;
    private javax.swing.JPanel Sidepane;
    private javax.swing.JPanel Viewbutton;
    private javax.swing.JTextField addfield;
    private javax.swing.JTextField dobfield;
    private javax.swing.JTextField emailfield;
    private javax.swing.JTextField firstnamefield;
    private javax.swing.JTextField idfield;
    private javax.swing.JTextField intakefield;
    private javax.swing.JTextField intakefield2;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField lastnamefield;
    private javax.swing.JTextField nationfield;
    private javax.swing.JTextField passfield;
    private javax.swing.JTextField phonefield;
    private javax.swing.JTextField racefield;
    private javax.swing.JTextField religionfield;
    private javax.swing.JTextField sexfield;
    private javax.swing.JTextField subjectfield;
    // End of variables declaration//GEN-END:variables
}
