/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package attendance.management.system;

import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Asus
 */
public class AdminSearch extends javax.swing.JFrame {

    
    public AdminSearch() {
        initComponents();
    }
    
    void setColor(JPanel panel){
        panel.setBackground(new Color(85,65,200));
    }
    
    void resetColor(JPanel panel){
        panel.setBackground(new Color(85,65,153));
        
    }
    
    void resetColor1(JPanel panel){
        panel.setBackground(new Color(204,204,255));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        BG = new javax.swing.JPanel();
        Sidepane = new javax.swing.JPanel();
        Registerbutton = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Profilebutton = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Viewbutton = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Searchbutton = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        Motifybutton = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        Namelabel = new javax.swing.JLabel();
        Attendancebutton = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        Exitbutton = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        student = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        lecturer = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        BG.setBackground(new java.awt.Color(255, 255, 255));
        BG.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        BG.setEnabled(false);
        BG.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                BGMouseMoved(evt);
            }
        });
        BG.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Sidepane.setBackground(new java.awt.Color(51, 0, 102));
        Sidepane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Registerbutton.setBackground(new java.awt.Color(85, 65, 153));
        Registerbutton.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                RegisterbuttonMouseMoved(evt);
            }
        });
        Registerbutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                RegisterbuttonMousePressed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Add User Male_48px_1.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Register");

        javax.swing.GroupLayout RegisterbuttonLayout = new javax.swing.GroupLayout(Registerbutton);
        Registerbutton.setLayout(RegisterbuttonLayout);
        RegisterbuttonLayout.setHorizontalGroup(
            RegisterbuttonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RegisterbuttonLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        RegisterbuttonLayout.setVerticalGroup(
            RegisterbuttonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        Sidepane.add(Registerbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 460, 330, -1));

        Profilebutton.setBackground(new java.awt.Color(85, 65, 153));
        Profilebutton.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                ProfilebuttonMouseMoved(evt);
            }
        });
        Profilebutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ProfilebuttonMousePressed(evt);
            }
        });
        Profilebutton.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/User_48px.png"))); // NOI18N
        Profilebutton.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 0, 61, 60));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Profile");
        Profilebutton.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(133, 0, 109, 60));

        Sidepane.add(Profilebutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 330, -1));

        Viewbutton.setBackground(new java.awt.Color(85, 65, 153));
        Viewbutton.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                ViewbuttonMouseMoved(evt);
            }
        });
        Viewbutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ViewbuttonMousePressed(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/View Details_48px.png"))); // NOI18N

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("View");

        javax.swing.GroupLayout ViewbuttonLayout = new javax.swing.GroupLayout(Viewbutton);
        Viewbutton.setLayout(ViewbuttonLayout);
        ViewbuttonLayout.setHorizontalGroup(
            ViewbuttonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ViewbuttonLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        ViewbuttonLayout.setVerticalGroup(
            ViewbuttonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        Sidepane.add(Viewbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 330, -1));

        Searchbutton.setBackground(new java.awt.Color(85, 65, 200));
        Searchbutton.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                SearchbuttonMouseMoved(evt);
            }
        });

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Search_48px.png"))); // NOI18N

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Search & Delete");

        javax.swing.GroupLayout SearchbuttonLayout = new javax.swing.GroupLayout(Searchbutton);
        Searchbutton.setLayout(SearchbuttonLayout);
        SearchbuttonLayout.setHorizontalGroup(
            SearchbuttonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SearchbuttonLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE)
                .addContainerGap())
        );
        SearchbuttonLayout.setVerticalGroup(
            SearchbuttonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        Sidepane.add(Searchbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 340, 330, -1));

        Motifybutton.setBackground(new java.awt.Color(85, 65, 153));
        Motifybutton.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                MotifybuttonMouseMoved(evt);
            }
        });
        Motifybutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                MotifybuttonMousePressed(evt);
            }
        });

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Change User_48px.png"))); // NOI18N

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Modify");

        javax.swing.GroupLayout MotifybuttonLayout = new javax.swing.GroupLayout(Motifybutton);
        Motifybutton.setLayout(MotifybuttonLayout);
        MotifybuttonLayout.setHorizontalGroup(
            MotifybuttonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MotifybuttonLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        MotifybuttonLayout.setVerticalGroup(
            MotifybuttonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        Sidepane.add(Motifybutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 400, 330, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Male User_96px.png"))); // NOI18N
        Sidepane.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, -1, 90));

        Namelabel.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        Namelabel.setForeground(new java.awt.Color(255, 255, 255));
        Namelabel.setText("User");
        Sidepane.add(Namelabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, -1, -1));

        Attendancebutton.setBackground(new java.awt.Color(85, 65, 153));
        Attendancebutton.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                AttendancebuttonMouseMoved(evt);
            }
        });
        Attendancebutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                AttendancebuttonMousePressed(evt);
            }
        });

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Classroom_48px.png"))); // NOI18N

        jLabel24.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("Attendance");

        javax.swing.GroupLayout AttendancebuttonLayout = new javax.swing.GroupLayout(Attendancebutton);
        Attendancebutton.setLayout(AttendancebuttonLayout);
        AttendancebuttonLayout.setHorizontalGroup(
            AttendancebuttonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AttendancebuttonLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        AttendancebuttonLayout.setVerticalGroup(
            AttendancebuttonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        Sidepane.add(Attendancebutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 520, 330, -1));

        BG.add(Sidepane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 330, 850));

        jPanel3.setBackground(new java.awt.Color(153, 102, 255));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 34)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Searching Profile");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Admin");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(jLabel12))
                .addContainerGap(233, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        BG.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 110, 600, 150));

        Exitbutton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Cancel_24px_1.png"))); // NOI18N
        Exitbutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ExitbuttonMousePressed(evt);
            }
        });
        BG.add(Exitbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 10, -1, -1));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Exit Sign_30px.png"))); // NOI18N
        jLabel14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel14MousePressed(evt);
            }
        });
        BG.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 7, -1, -1));

        student.setBackground(new java.awt.Color(204, 204, 255));
        student.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                studentMouseMoved(evt);
            }
        });
        student.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                studentMousePressed(evt);
            }
        });

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Student Female_96px.png"))); // NOI18N

        jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel17.setText("Student");

        javax.swing.GroupLayout studentLayout = new javax.swing.GroupLayout(student);
        student.setLayout(studentLayout);
        studentLayout.setHorizontalGroup(
            studentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, studentLayout.createSequentialGroup()
                .addContainerGap(58, Short.MAX_VALUE)
                .addGroup(studentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16)
                    .addGroup(studentLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel17)))
                .addGap(56, 56, 56))
        );
        studentLayout.setVerticalGroup(
            studentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(studentLayout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel17)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        BG.add(student, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 370, -1, -1));

        lecturer.setBackground(new java.awt.Color(204, 204, 255));
        lecturer.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lecturerMouseMoved(evt);
            }
        });
        lecturer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lecturerMousePressed(evt);
            }
        });

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Training_96px.png"))); // NOI18N

        jLabel18.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel18.setText("Lecturer");

        javax.swing.GroupLayout lecturerLayout = new javax.swing.GroupLayout(lecturer);
        lecturer.setLayout(lecturerLayout);
        lecturerLayout.setHorizontalGroup(
            lecturerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lecturerLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(lecturerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel15)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(62, Short.MAX_VALUE))
        );
        lecturerLayout.setVerticalGroup(
            lecturerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lecturerLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel18)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        BG.add(lecturer, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 370, -1, 210));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BG, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BG, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BGMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BGMouseMoved
        // TODO add your handling code here:
        setColor(Searchbutton);
        resetColor(Profilebutton);
        resetColor(Viewbutton);
        resetColor(Motifybutton);
        resetColor(Attendancebutton);
        resetColor(Registerbutton);
        resetColor1(student);
        resetColor1(lecturer);
    }//GEN-LAST:event_BGMouseMoved

    private void ViewbuttonMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ViewbuttonMouseMoved
        // TODO add your handling code here:
        setColor(Viewbutton);
        resetColor(Profilebutton);
        resetColor(Searchbutton);
        resetColor(Motifybutton);
        resetColor(Attendancebutton);
        resetColor(Registerbutton);
    }//GEN-LAST:event_ViewbuttonMouseMoved

    private void SearchbuttonMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SearchbuttonMouseMoved
        // TODO add your handling code here:
        setColor(Searchbutton);
        resetColor(Profilebutton);
        resetColor(Viewbutton);
        resetColor(Motifybutton);
        resetColor(Attendancebutton);
        resetColor(Registerbutton);
    }//GEN-LAST:event_SearchbuttonMouseMoved

    private void MotifybuttonMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MotifybuttonMouseMoved
        // TODO add your handling code here:
        setColor(Motifybutton);
        resetColor(Profilebutton);
        resetColor(Searchbutton);
        resetColor(Viewbutton);
        resetColor(Attendancebutton);
        resetColor(Registerbutton);
    }//GEN-LAST:event_MotifybuttonMouseMoved

    private void RegisterbuttonMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegisterbuttonMouseMoved
        // TODO add your handling code he
        setColor(Registerbutton);
        resetColor(Profilebutton);
        resetColor(Searchbutton);
        resetColor(Motifybutton);
        resetColor(Viewbutton);
        resetColor(Attendancebutton);
    }//GEN-LAST:event_RegisterbuttonMouseMoved

    private void AttendancebuttonMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AttendancebuttonMouseMoved
        // TODO add your handling code here:
        setColor(Attendancebutton);
        resetColor(Profilebutton);
        resetColor(Searchbutton);
        resetColor(Motifybutton);
        resetColor(Viewbutton);
        resetColor(Registerbutton);
    }//GEN-LAST:event_AttendancebuttonMouseMoved

    private void ProfilebuttonMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ProfilebuttonMouseMoved
        // TODO add your handling code here:
        setColor(Profilebutton);
        resetColor(Attendancebutton);
        resetColor(Searchbutton);
        resetColor(Motifybutton);
        resetColor(Viewbutton);
        resetColor(Registerbutton);
    }//GEN-LAST:event_ProfilebuttonMouseMoved

    private void ProfilebuttonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ProfilebuttonMousePressed
        // TODO add your handling code here:
        Admin profile = new Admin();
        profile.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_ProfilebuttonMousePressed

    private void ExitbuttonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitbuttonMousePressed
        // TODO add your handling code here:
        int closeprogram = JOptionPane.showConfirmDialog(null,"Do you want to exit system?","Exit",
                JOptionPane.YES_NO_OPTION);
        if (closeprogram == JOptionPane.YES_OPTION)
        {
        System.exit(0);
        }
    }//GEN-LAST:event_ExitbuttonMousePressed

    private void ViewbuttonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ViewbuttonMousePressed
        // TODO add your handling code here:
        AdminView view = new AdminView();
        view.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_ViewbuttonMousePressed

    private void MotifybuttonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MotifybuttonMousePressed
        // TODO add your handling code here:
        AdminMotify motify = new AdminMotify();
        motify.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_MotifybuttonMousePressed

    private void RegisterbuttonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegisterbuttonMousePressed
        // TODO add your handling code here:
        AdminRegister delete = new AdminRegister();
        delete.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_RegisterbuttonMousePressed

    private void AttendancebuttonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AttendancebuttonMousePressed
        // TODO add your handling code here:
        AdminAttendance attendance = new AdminAttendance();
        attendance.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_AttendancebuttonMousePressed

    private void jLabel14MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MousePressed
        // TODO add your handling code here:
        int logout = JOptionPane.showConfirmDialog(null,"Do you want to logout ID?","Logout",
            JOptionPane.YES_NO_OPTION);
        if (logout == JOptionPane.YES_OPTION)
        {
            Loginpage login = new Loginpage();
            login.setVisible(true);
            this.setVisible(false);
        }
    }//GEN-LAST:event_jLabel14MousePressed

    private void studentMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_studentMousePressed
        AdminSearchstudent v = new AdminSearchstudent();
        v.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_studentMousePressed

    private void lecturerMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lecturerMousePressed
        AdminSearchlecturer v = new AdminSearchlecturer();
        v.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_lecturerMousePressed

    private void lecturerMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lecturerMouseMoved
        // TODO add your handling code here:
        setColor(lecturer);
        resetColor1(student);
    }//GEN-LAST:event_lecturerMouseMoved

    private void studentMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_studentMouseMoved
        // TODO add your handling code here:
        setColor(student);
        resetColor1(lecturer);
    }//GEN-LAST:event_studentMouseMoved

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        adminclass a = new adminclass();
        String name = a.full();
        Namelabel.setText(name);
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminSearch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminSearch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminSearch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminSearch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminSearch().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Attendancebutton;
    private javax.swing.JPanel BG;
    private javax.swing.JLabel Exitbutton;
    private javax.swing.JPanel Motifybutton;
    private javax.swing.JLabel Namelabel;
    private javax.swing.JPanel Profilebutton;
    private javax.swing.JPanel Registerbutton;
    private javax.swing.JPanel Searchbutton;
    private javax.swing.JPanel Sidepane;
    private javax.swing.JPanel Viewbutton;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel lecturer;
    private javax.swing.JPanel student;
    // End of variables declaration//GEN-END:variables
}
